[package]
name = "check"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
rational = "1.7.0"
rayon = "1.10.0"
regex = "1.11.1"

[features]
big-tests = []
emoji = []

[profile.release]
codegen-units = 1
lto = "fat"
